# Generated by Django 5.2.7 on 2025-10-17 18:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miproyecto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='uui',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
