# Generated by Django 5.2.7 on 2025-10-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miproyecto', '0002_person_uui'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=100)),
                ('propic', models.ImageField(blank=True, default='users/default_user.png', upload_to='users/')),
            ],
        ),
    ]
