# Generated by Django 5.2.7 on 2025-10-25 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miproyecto', '0005_persona_alter_profile_person_delete_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='uui',
            new_name='uuid',
        ),
    ]
