# Generated by Django 5.2.7 on 2025-10-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miproyecto', '0006_rename_uui_persona_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='propic',
            field=models.ImageField(blank=True, default='users/default_user.png', upload_to=''),
        ),
    ]
