# Generated by Django 5.2.7 on 2025-10-26 17:43

import django.db.models.deletion
import miproyecto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miproyecto', '0007_persona_propic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birth', models.DateField()),
                ('slug', models.SlugField(unique=True)),
                ('mail', models.CharField(default='', max_length=100)),
                ('propic', models.ImageField(blank=True, default='users/default_user.png', upload_to=miproyecto.models.user_directory_path)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='miproyecto.person'),
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
