# Generated by Django 5.2.7 on 2025-11-02 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sala', models.CharField(max_length=100, unique=True)),
                ('tablero', models.CharField(default='         ', max_length=9)),
                ('jugador_actual', models.CharField(default='X', max_length=1)),
                ('estado_juego', models.CharField(choices=[('ACTIVO', 'Activo'), ('X_GANO', 'X Ganó'), ('O_GANO', 'O Ganó'), ('EMPATE', 'Empate')], default='ACTIVO', max_length=10)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
