# Generated by Django 5.2.7 on 2025-11-10 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='jugador_o',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='juegos_como_o', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='juego',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juegos_como_x', to=settings.AUTH_USER_MODEL),
        ),
    ]
