# Generated by Django 5.2.7 on 2025-11-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_juego_jugador_o_alter_juego_propietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='estado_juego',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('X_GANO', 'X Gano'), ('O_GANO', 'O Gano'), ('EMPATE', 'Empate')], default='ACTIVO', max_length=10),
        ),
    ]
